/**
 * Regenerates the dashboard of a review report written per report-format.md.
 *
 * The findings are the source of truth; the dashboard is derived. This script
 * reads the finding headers, groups them by state, and rewrites everything
 * between the "## Dashboard" heading and the next "## " heading with one
 * section per state present, each listing links to its findings. Lines inside
 * fenced code blocks and inside the dashboard itself are ignored, so quoted
 * examples and the previous run's output never count as findings.
 *
 * Header shape, defined in report-format.md:
 *   ### <state> <severity> <ID> — <title>
 *
 * Links follow the GitHub heading-slug rule: lower-cased, every character
 * outside [a-z0-9 _-] dropped, spaces turned into hyphens.
 *
 * Usage: node update-dashboard.ts <report.md>
 *
 * Requires Node 24 or newer — it runs this TypeScript file directly, with no
 * build step and no dependencies.
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";

interface State {
  marker: string;
  label: string;
}

interface Finding {
  id: string;
  state: string;
  anchor: string;
}

const STATES: State[] = [
  { marker: "⏳", label: "awaiting triage" },
  { marker: "❓", label: "unverified" },
  { marker: "✅", label: "approved" },
  { marker: "🔧", label: "fixed" },
  { marker: "❌", label: "discarded" },
  { marker: "📌", label: "deferred" },
  { marker: "🔀", label: "improvement" },
];

const HEADING = /^###\s+(?<rest>.*\S)\s*$/u;
const FINDING =
  /^(?<state>\S+)\s+(?<severity>\S+)\s+(?<id>[A-Za-z0-9-]+)\s+—\s+(?<title>.+)$/u;
const FENCE = /^\s*(?<marker>`{3,}|~{3,})/u;
const SECTION = /^##\s+(?<title>.*\S)\s*$/u;

function slug(heading: string): string {
  return heading
    .toLowerCase()
    .replace(/[^a-z0-9 _-]/gu, "")
    .replace(/ /gu, "-");
}

function build(findings: Finding[]): string[] {
  const block = [
    "## Dashboard",
    "",
    "<!-- generated by update-dashboard.ts — do not edit by hand -->",
    "",
  ];
  if (findings.length === 0) {
    block.push("**No findings** — the review raised none.", "");
    return block;
  }
  for (const state of STATES) {
    const listed = findings.filter((finding) => finding.state === state.marker);
    if (listed.length === 0) continue;
    block.push(`### ${state.marker} ${listed.length} ${state.label}`, "");
    listed.forEach((finding, index) => {
      block.push(`  ${index + 1}. [${finding.id}](#${finding.anchor})`);
    });
    block.push("");
  }
  return block;
}

function main(): void {
  const path = process.argv[2];
  if (!path) throw new Error("usage: node update-dashboard.ts <report.md>");
  if (!existsSync(path)) throw new Error(`report not found: ${path}`);

  const raw = readFileSync(path, "utf8");
  const newline = raw.includes("\r\n") ? "\r\n" : "\n";
  const lines = raw.split(/\r?\n/u);

  const findings: Finding[] = [];
  const unknown: string[] = [];
  let fence: string | null = null;
  let start = -1;
  let end = -1;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    const fenced = FENCE.exec(line);
    if (fenced) {
      const marker = fenced.groups!.marker;
      if (fence === null) fence = marker;
      else if (marker[0] === fence[0] && marker.length >= fence.length) fence = null;
      continue;
    }
    if (fence !== null) continue;

    const section = SECTION.exec(line);
    if (section) {
      if (section.groups!.title === "Dashboard") start = i;
      else if (start >= 0 && end < 0) end = i;
      continue;
    }

    const heading = HEADING.exec(line);
    if (!heading) continue;
    if (start >= 0 && end < 0) continue; // the dashboard's own sections

    const finding = FINDING.exec(heading.groups!.rest);
    if (!finding) {
      console.warn(`update-dashboard: ignoring malformed finding header, line ${i + 1}: ${line}`);
      continue;
    }
    const state = finding.groups!.state;
    if (!STATES.some((known) => known.marker === state)) unknown.push(`${finding.groups!.id} (${state})`);
    findings.push({
      id: finding.groups!.id,
      state,
      anchor: slug(heading.groups!.rest),
    });
  }

  if (start < 0) throw new Error(`no '## Dashboard' heading in ${path}`);
  if (unknown.length > 0)
    throw new Error(`unknown state marker on ${unknown.join(", ")} — see the states table in report-format.md`);
  if (end < 0) end = lines.length;

  const updated = [...lines.slice(0, start), ...build(findings), ...lines.slice(end)];
  writeFileSync(path, updated.join(newline), "utf8");
  console.log(`Dashboard updated: ${findings.length} findings in ${path}`);
}

try {
  main();
} catch (error) {
  console.error(`update-dashboard: ${(error as Error).message}`);
  process.exit(1);
}
