/**
 * Regenerates the dashboard of a review report written per report-format.md.
 *
 * The findings are the source of truth; the dashboard is derived. This script
 * reads the finding headers of the `## Findings` section, groups them by
 * state, and rewrites everything between the "## Dashboard" heading and the
 * "## Findings" heading with one section per state present, each listing
 * links to its findings. Lines inside fenced code blocks are ignored, so
 * quoted examples never count as findings.
 *
 * The structure contract of report-format.md is a precondition: each break it
 * lists — a fence left open, the title, the sections, the intro's entries, a
 * finding header's place or shape, an unknown marker, a duplicate or
 * out-of-sequence ID, a finding missing a subsection — makes the script name
 * the offending line and write nothing, rather than rewrite a document it
 * cannot read. scaffold-report.ts writes that structure.
 *
 * Header shape, defined in report-format.md:
 *   ### <state> <severity> <ID> — <title>
 *
 * Links follow the GitHub heading-slug rule: lower-cased, every character
 * outside [a-z0-9 _-] dropped, spaces turned into hyphens.
 *
 * Usage: node update-dashboard.ts <report.md>
 *
 * Requires Node 24 or newer — it runs this TypeScript file directly, with no
 * build step and no dependencies.
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";

interface State {
  marker: string;
  label: string;
}

interface Finding {
  id: string;
  state: string;
  anchor: string;
}

const STATES: State[] = [
  { marker: "⏳", label: "awaiting triage" },
  { marker: "❓", label: "unverified" },
  { marker: "✅", label: "approved" },
  { marker: "🔧", label: "fixed" },
  { marker: "❌", label: "discarded" },
  { marker: "📌", label: "deferred" },
  { marker: "🔀", label: "improvement" },
];

const SEVERITIES = ["🔴", "🟡", "⚪"];

const HEADING = /^###\s+(?<rest>.*\S)\s*$/u;
const SUBHEADING = /^####\s+(?<title>.*\S)\s*$/u;
const FINDING =
  /^(?<state>\S+)\s+(?<severity>\S+)\s+(?<id>[A-Za-z0-9-]+)\s+—\s+(?<title>.+)$/u;
const FENCE = /^\s*(?<marker>`{3,}|~{3,})/u;
const SECTION = /^##\s+(?<title>.*\S)\s*$/u;
const TITLE = /^#\s+(?<rest>.*\S)\s*$/u;
const ID = /^F(?<number>\d+)$/u;
const ENTRY = /^\s*(?:-\s+)?\*\*(?<label>[^*]+)\*\*/u;
const SECTIONS = ["Intro", "Dashboard", "Findings"];
const ENTRIES = ["Reviewed", "Rules", "Commits", "Status"];
const SUBSECTIONS = ["Description", "Updates"];

function slug(heading: string): string {
  return heading
    .toLowerCase()
    .replace(/[^a-z0-9 _-]/gu, "")
    .replace(/ /gu, "-");
}

function build(findings: Finding[]): string[] {
  const block = [
    "## Dashboard",
    "",
    "<!-- generated by update-dashboard.ts — do not edit by hand -->",
    "",
  ];
  if (findings.length === 0) {
    block.push("**No findings** — the review raised none.", "");
    return block;
  }
  for (const state of STATES) {
    const listed = findings.filter((finding) => finding.state === state.marker);
    if (listed.length === 0) continue;
    block.push(`### ${state.marker} ${listed.length} ${state.label}`, "");
    listed.forEach((finding, index) => {
      block.push(`  ${index + 1}. [${finding.id}](#${finding.anchor})`);
    });
    block.push("");
  }
  return block;
}

function main(): void {
  const path = process.argv[2];
  if (!path) throw new Error("usage: node update-dashboard.ts <report.md>");
  if (!existsSync(path)) throw new Error(`report not found: ${path}`);

  const raw = readFileSync(path, "utf8");
  const newline = raw.includes("\r\n") ? "\r\n" : "\n";
  const lines = raw.split(/\r?\n/u);

  const findings: Finding[] = [];
  const unknown: string[] = [];
  const misplaced: string[] = [];
  const malformed: string[] = [];
  const idLines = new Map<string, number[]>();
  const misshaped: string[] = [];
  const disordered: string[] = [];
  let previous: number | null = null;
  const titles: { text: string; line: number }[] = [];
  const sections: { title: string; line: number }[] = [];
  const entries = new Set<string>();
  const blocks: { id: string; line: number; parts: Set<string> }[] = [];
  let fence: string | null = null;
  let fenceLine = 0;
  let inFindings = false;
  let inIntro = false;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    const fenced = FENCE.exec(line);
    if (fenced) {
      const marker = fenced.groups!.marker;
      if (fence === null) {
        fence = marker;
        fenceLine = i + 1;
      } else if (marker[0] === fence[0] && marker.length >= fence.length) fence = null;
      continue;
    }
    if (fence !== null) continue;

    const section = SECTION.exec(line);
    if (section) {
      const title = section.groups!.title;
      sections.push({ title, line: i });
      inFindings = title === "Findings";
      inIntro = title === "Intro";
      continue;
    }

    if (inIntro) {
      const entry = ENTRY.exec(line);
      if (entry) entries.add(entry.groups!.label.trim());
    }

    const heading = HEADING.exec(line);
    if (!heading) {
      const subheading = SUBHEADING.exec(line);
      if (subheading && blocks.length > 0 && inFindings)
        blocks[blocks.length - 1].parts.add(subheading.groups!.title);
      if (!subheading) {
        const title = TITLE.exec(line);
        if (title) titles.push({ text: title.groups!.rest, line: i });
      }
      continue;
    }

    const finding = FINDING.exec(heading.groups!.rest);
    if (!inFindings) {
      if (finding) misplaced.push(`line ${i + 1}: ${line.trim()}`);
      continue;
    }
    if (!finding) {
      malformed.push(`line ${i + 1}: ${line.trim()}`);
      continue;
    }
    const state = finding.groups!.state;
    const severity = finding.groups!.severity;
    const id = finding.groups!.id;
    if (!STATES.some((known) => known.marker === state))
      unknown.push(`line ${i + 1}: state '${state}'`);
    if (!SEVERITIES.includes(severity))
      unknown.push(`line ${i + 1}: severity '${severity}'`);
    idLines.set(id, [...(idLines.get(id) ?? []), i + 1]);
    const shaped = ID.exec(id);
    if (!shaped) misshaped.push(`line ${i + 1}: ${id}`);
    else {
      const number = Number(shaped.groups!.number);
      if (previous !== null && number <= previous)
        disordered.push(`line ${i + 1}: ${id} after F${previous}`);
      previous = number;
    }
    findings.push({
      id,
      state,
      anchor: slug(heading.groups!.rest),
    });
    blocks.push({ id, line: i + 1, parts: new Set<string>() });
  }

  const scaffold = "scaffold the document with scaffold-report.ts";
  const expected = SECTIONS.map((title) => `## ${title}`).join(", ");
  if (fence !== null)
    throw new Error(
      `the fence opened in ${path}, line ${fenceLine}, is never closed — everything below it reads as quoted text`,
    );
  if (titles.length === 0) throw new Error(`no '# Review — <target>' title in ${path} — ${scaffold}`);
  if (titles.length > 1)
    throw new Error(
      `more than one title in ${path}, lines ${titles.map((title) => title.line + 1).join(", ")} — ${scaffold}`,
    );
  if (!/^Review — \S/u.test(titles[0].text))
    throw new Error(
      `title in ${path}, line ${titles[0].line + 1}, reads '# ${titles[0].text}' — expected '# Review — <target>'`,
    );
  const seen = new Set<string>();
  for (const section of sections) {
    const at = `${path}, line ${section.line + 1}`;
    if (!SECTIONS.includes(section.title))
      throw new Error(`unexpected section '## ${section.title}' in ${at} — the report holds ${expected} and nothing else`);
    if (seen.has(section.title))
      throw new Error(`'## ${section.title}' appears twice in ${at} — ${scaffold}`);
    seen.add(section.title);
  }
  for (const title of SECTIONS)
    if (!seen.has(title)) throw new Error(`no '## ${title}' section in ${path} — ${scaffold}`);
  const order = sections.findIndex((section, index) => section.title !== SECTIONS[index]);
  if (order >= 0)
    throw new Error(
      `sections out of order in ${path}, line ${sections[order].line + 1}: '## ${sections[order].title}' where '## ${SECTIONS[order]}' belongs — the report reads ${sections.map((section) => `## ${section.title}`).join(", ")}, expected ${expected}`,
    );
  if (titles[0].line > sections[0].line)
    throw new Error(
      `the title comes after '## ${sections[0].title}' in ${path}, line ${titles[0].line + 1} — ${scaffold}`,
    );
  if (misplaced.length > 0)
    throw new Error(
      `finding header outside '## Findings' in ${path} — ${misplaced.join("; ")} — move it into the findings section`,
    );
  if (malformed.length > 0)
    throw new Error(
      `malformed finding header in ${path} — ${malformed.join("; ")} — expected '### <state> <severity> <ID> — <title>'`,
    );
  if (unknown.length > 0)
    throw new Error(
      `unknown marker in ${path} — ${unknown.join("; ")} — see the states table and the severity scale in report-format.md`,
    );
  const reused = [...idLines].filter(([, at]) => at.length > 1);
  if (reused.length > 0)
    throw new Error(
      `duplicate finding ID in ${path} — ${reused.map(([id, at]) => `${id} on lines ${at.join(", ")}`).join("; ")} — an ID is never reused`,
    );
  if (misshaped.length > 0)
    throw new Error(
      `finding ID out of shape in ${path} — ${misshaped.join("; ")} — an ID reads F<n>, as F7`,
    );
  if (disordered.length > 0)
    throw new Error(
      `finding IDs out of order in ${path} — ${disordered.join("; ")} — they rise down the section`,
    );
  const missingEntries = ENTRIES.filter((entry) => !entries.has(entry));
  if (missingEntries.length > 0)
    throw new Error(
      `intro entry missing in ${path} — ${missingEntries.map((entry) => `**${entry}**`).join(", ")} — the intro carries ${ENTRIES.map((entry) => `**${entry}**`).join(", ")}`,
    );
  const incomplete = blocks
    .map((block) => ({ block, missing: SUBSECTIONS.filter((part) => !block.parts.has(part)) }))
    .filter(({ missing }) => missing.length > 0);
  if (incomplete.length > 0)
    throw new Error(
      `finding subsection missing in ${path} — ${incomplete
        .map(({ block, missing }) => `${block.id} on line ${block.line} has no ${missing.map((part) => `'#### ${part}'`).join(" or ")}`)
        .join("; ")} — every finding carries '#### Description' and '#### Updates'`,
    );

  const start = sections.find((section) => section.title === "Dashboard")!.line;
  const end = sections.find((section) => section.title === "Findings")!.line;
  const updated = [...lines.slice(0, start), ...build(findings), ...lines.slice(end)];
  writeFileSync(path, updated.join(newline), "utf8");
  console.log(`Dashboard updated: ${findings.length} findings in ${path}`);
}

try {
  main();
} catch (error) {
  console.error(`update-dashboard: ${(error as Error).message}`);
  process.exit(1);
}
